### ISSUE TITLE
End of stack trace

### ISSUE THREAD

**Issue by JefferyMichael1** [PocketMobsters/MobBotTemp#24]
![untitled](https://cloud.githubusercontent.com/assets/21020943/17648717/9e993466-61ed-11e6-9782-9b28aba59990.png)

**Comment by bmdr38** [comment]
Yea... I got this on one of my accounts as well.  Basically youre able to log in, but once it tries to get your inventory, you get this exception because it doesnt return an inventory.

From what I understand, this is one of the types of bans as well, being on device id.  You can test this by renaming your config to something like config_backup.json and let the bot regenerate a new one, with a new device id.

I would also recommend waiting a few hours before doing this, as you might get flagged immediately for switching too soon.  So just have some patience, wait a while, and try again later with a new device id settings.

**Comment by xfaustx** [comment]
I have same thing on PTC acc looks like its a ip ban...
