### ISSUE TITLE
Bot didn't auto favorite pokemon according to set parameters

### ISSUE THREAD

**Issue by boreslayer** [PocketMobsters/MobBotTemp#53]
The bot doesn't auto favorite high IV pokemon that I have sniped using PokeSniper even those i set auto favorite to true in the config files.  I did not run them concurrently.  I ran PokeSniper for awhile and then switched to PokeMobBot.

**Comment by XeonPowder** [comment]
![beabc8a870b4e9d7d9009bf62308a53d](https://cloud.githubusercontent.com/assets/2179775/17655625/091d0aa0-6276-11e6-971f-f4e6edabf5d4.png)

**Comment by boreslayer** [comment]
That's weird.  It didn't do that for mine.

**Comment by WORMSS** [comment]
I've never had the favourite feature work. Though, I have never tried `"FavoriteMinIvPercentage": 1.0` but that is a little low for what I wanted. I currently have it set to `90.0`, and none of the over 90% are Favorited.

**Comment by bmdr38** [comment]
It was implemented recently, though I have not checked if it actually does the favoriting via a real device

**Comment by WORMSS** [comment]
Ahh, I've seen the Auto Favourite feature in the config before the whole API change. But I had never been that bothered since I only had 3 above (at that point) 95%, but now that I lowered it to 90, I still didn't see it favourite anything. But then there was the TakeDown notice and stuff, so I it wasn't exactly a priority. But since someone else brought it up, I just wanted to add my +1 to it.

**Comment by XeonPowder** [comment]
![4c789f1f241c9764c15bfcd78c94a42c](https://cloud.githubusercontent.com/assets/2179775/17662078/ac7d34d6-62a8-11e6-9b0b-e832a3c931d8.png)

**Comment by XeonPowder** [comment]
works.
